version: '3.7'

services:
  web:
    container_name: undegasescacum_django
    build:
        context: .
        dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/opt/undegasescacum/
    ports:
      - "8000:8000"
    env_file:
      - .env