# Generated by Django 3.0.5 on 2020-04-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceunit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ServiceUnitCategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='serviceunit',
            name='link',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceunit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ServiceUnitLocation', verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='serviceunit',
            name='schedule',
            field=models.CharField(max_length=250, verbose_name='Program de functionare'),
        ),
        migrations.AlterField(
            model_name='serviceunit',
            name='tags',
            field=models.TextField(verbose_name='Ce se gaseste acolo'),
        ),
    ]
